### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by zhang-jinyi** [jinxing94/subword2vec#1]
Hi,
I want to have a try on it,
but could you tell me how to get:
corpus_file = 'datasets/zh_wiki_01_segment_post'
sub_file = 'datasets/items_httpcn_6.jl'
OR tell me how to make them by myself.
Thanks.

**Comment by jinxing94** [comment]
Hi,
I have refined the project. Please see https://github.com/HKUST-KnowComp/JWE
Best regards
